version: '{build}'
skip_tags: true
image: Visual Studio 2022
install:
build_script:
  - pwsh: ./Build.ps1
test: off
artifacts:
  - path: artifacts/Seq.App.*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: oy2cbptzf62r3wo5i5lak6oi4z5tddwunf6pdqojdqgdye
    skip_symbols: true
    on:
      branch: /^(main|dev)$/
  - provider: GitHub
    auth_token:
      secure: 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
    artifact: /Seq.App.*\.nupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: main
